// Copyright 2026 Chesapeake Computing
// SPDX-License-Identifier: Apache-2.0

import { dirname, join } from "@std/path";

type SkillAgent = "codex" | "claude" | "opencode" | "cursor";
type SkillName = "dn" | "base-image" | "rfc";
type SkillScope = "repo" | "user";
type InstallStatus = "write" | "skip" | "conflict";

interface InitAgentsOptions {
  skill: boolean;
  skillName: SkillName;
  agent?: SkillAgent;
  scope: SkillScope;
  dryRun: boolean;
  json: boolean;
  force: boolean;
}

interface InstallableSkill {
  name: SkillName;
  skillMarkdown: string;
  openAiMetadata: string;
}

interface SkillTarget {
  path: string;
  content: string;
}

interface InstallResult {
  path: string;
  status: InstallStatus;
  reason: string;
}

const SUPPORTED_SKILL_AGENTS = [
  "codex",
  "claude",
  "opencode",
  "cursor",
] as const;
const SUPPORTED_SKILL_NAMES = ["dn", "base-image", "rfc"] as const;
const GENERATED_MARKER = "Generated by dn init agents --skill";
const MARKDOWN_MANAGED_MARKER = `<!-- ${GENERATED_MARKER}. -->`;
const YAML_MANAGED_MARKER = `# ${GENERATED_MARKER}.`;

const DN_SKILL_CONTENT = `---
name: dn
description: Use when interacting with the dn CLI for GitHub issues, kickstart, meld, loop, land, VCS sync, and plan-backed execution. Outer IDE harnesses implement with the CLI, then ask before committing.
---

${MARKDOWN_MANAGED_MARKER}

# dn

\`dn\` is a Deno-based CLI for GitHub issue-driven development workflows. It is
the primary interface to this repository's workflows. Prefer it over ad-hoc
scripts or direct API calls when preparing workspaces, iterating on plans, or
coordinating changes.

## Quickstart

\`\`\`bash
dn                    # list subcommands
dn <subcommand> -h    # help for a specific subcommand
\`\`\`

## Project config (\`dn.json\`)

At the start of a session, read repository \`dn.json\` (workspace root, or walk
up). If \`harness_hints\` is present, apply it: a map of string keys to string
values with project-specific operator notes. Keys are freeform. Honor those
notes for this checkout. Do not put secrets in \`harness_hints\`.

## Repeatable flows

Default publish mode is local (\`none\`). Do not stack another kickstart on
uncommitted kickstart work.

When you are an **outer IDE harness**, implement with the CLI, then **ask**
whether to commit after a local (\`none\`) run. If the user says yes, you write
the commit with the repo VCS and omit \`*.plan.md\`. Do not auto-run \`dn land\`.
After \`--publish pr\` or \`--publish direct\`, kickstart already published —
report the PR URL or branch instead of committing here.

\`dn land\` is for attended CLI, CI, denoise/device-runners, \`--issue-testplan\`,
RFC land, or when the user names \`dn land\`. \`dn sync\` publishes to trunk; it
is not a commit step.

### kickstart

The common prompt is \`{github issue url} can you kickstart this?\` Resolve argv.
Do not quiz the user for flags the CLI already defaults.

1. Pass the **full issue URL** as the positional argument (not a bare number).
2. Compare the URL's \`owner/repo\` to this workspace
   (\`gh repo view --json nameWithOwner -q .nameWithOwner\`). If they differ,
   pass \`--allow-cross-repo\` (\`-A\`). Do not ask. Mention it in the summary. If
   you cannot detect the workspace repo, pass \`-A\` for a full URL anyway.
3. Extra guidance in the user message besides the URL → \`--steer "…"\`.
4. Named or attached files → \`--context-file\` (repeatable).
5. Leave the rest at CLI defaults unless the user asked:
   - publish \`none\` unless they asked for a PR or \`--publish direct\` (see
     Publish)
   - nested agent from project config / \`DN_AGENT\` (no \`--agent cursor\`)
   - no \`--cursor-cloud\`, \`--sandbox\`, \`--milestone\`, \`--complete\`, \`--once\`,
     \`--skip-plan\`, \`--verbosity\`, \`--workspace-root\`, \`--denoise-task\`
6. \`/pull/\` URL → \`dn fixup\`, not kickstart. Local \`.md\` → kickstart that file.
7. If \`plans/*.plan.md\` exists and the tree is dirty, stop and ask before
   stacking another kickstart.

\`\`\`bash
dn kickstart https://github.com/owner/repo/issues/123
dn kickstart --allow-cross-repo https://github.com/other/repo/issues/123
dn kickstart --steer "Focus on the parser" https://github.com/owner/repo/issues/123
# then ask: commit now?
\`\`\`

### Publish

An issue URL alone is \`--publish none\`. Map explicit user intent:

| User says | Argv | After success |
| --- | --- | --- |
| "open/create a PR", "as a PR", \`--awp\`, \`--publish pr\` | \`--publish pr\` | Report the PR URL. Do not also commit in this chat. |
| "publish direct", \`--publish direct\`, "push to trunk/main as part of kickstart" | \`--publish direct\` | Report the default branch. Do not also commit here or run \`dn sync\` unless they asked. |
| "publish" with no PR vs direct | Ask which | — |

\`--awp\` is an alias for \`--publish pr\`. Prefer \`--publish pr\` when constructing
argv. Direct commits and pushes to the default branch inside kickstart (lint
only). It is not \`dn sync\`.

\`\`\`bash
# "kickstart this and open a PR"
dn kickstart --publish pr https://github.com/owner/repo/issues/123

# "kickstart this with --publish direct"
dn kickstart --publish direct https://github.com/owner/repo/issues/123
\`\`\`

### meld → loop

\`\`\`bash
dn meld <issue-url-or-number>
dn loop plans/task.plan.md
# then ask: commit now?
\`\`\`

After \`dn fixup\`, ask before committing (same as kickstart).

## Common commands

\`\`\`bash
dn kickstart <issue-url-or-number>         # Full plan + implement workflow
dn meld <issue-url-or-number>              # Plan phase
dn loop plans/task.plan.md                 # Implement from an existing plan
dn land [plans/task.plan.md]               # Close out into VCS commits
dn land --single plans/task.plan.md        # One deterministic commit, no agent
dn fixup <pull-request-url>                # Address PR review feedback
dn meld a.md b.md --plan-name merged       # Plan from combined sources
dn init stack 42                           # Create a milestone task stack
dn sync                                    # Rebase onto trunk and publish
\`\`\`

## Global Flags

| Flag                    | Effect                                                           |
| ----------------------- | ---------------------------------------------------------------- |
| \`--agent <agent>\`       | \`<harness>:<model>\` (harness-only or optional \`:<thinking>\`)     |
| \`--context-file <path>\` | Include a file in agent prompt context (repeatable)                |
| \`--unattended\` / \`--ci\` | Non-interactive output                                             |
| \`--trace\`               | Live-stream agent harness output (default in CI)                   |
| \`--no-trace\`            | Suppress live agent stream (default in attended TTY)               |
| \`--no-color\`            | Disable ANSI color                                                 |
| \`--color\`               | Force ANSI color even on non-TTY                                   |
| \`--json\`                | JSON output where supported                                        |

### Agent harness selection priority

1. Explicit \`--agent <harness>:<model>\` (global or on the subcommand)
2. \`DN_AGENT\` using the same value form
3. Environment toggle: \`CURSOR_ENABLED=1\`, \`CLAUDE_ENABLED=1\`, \`CODEX_ENABLED=1\`, or \`COPILOT_ENABLED=1\`
4. Project \`dn.json\` / \`.github/dn/config.json\` harness name
5. Default: OpenCode

## Token resolution order

1. \`GITHUB_TOKEN\` or \`DANGEROUS_GITHUB_TOKEN\` environment variable
2. \`gh auth token\` (preferred interactive path: \`gh auth login\`)
3. \`dn auth\` cached device-flow token in \`~/.config/dn/\` (complementary)

## Common environment variables

- \`ISSUE\` - fallback issue URL or number for \`kickstart\` and \`meld\`
- \`WORKSPACE_ROOT\` - project root directory
- \`GITHUB_TOKEN\` - GitHub personal access token
- \`PR_URL\` - PR URL for \`fixup\`
- \`PLAN\` - path to plan file for \`loop\`

## RFCs and design context

Before large design work or multi-issue architecture changes, check whether this
repo has an RFC corpus:

\`\`\`bash
dn rfc list
# read files under rfcs/ when present
\`\`\`

- Prefer **RFCs** (\`rfcs/\`) for durable **why/how** design decisions
- Use **\`plans/\`** only for single-issue execution (meld, loop, kickstart)
- Bootstrap a new corpus with the **rfc** skill:
  \`dn init agents --skill rfc --agent <harness>\`
- First-run setup: \`dn init wizard --project\` (can run \`dn rfc init\`)

Use \`dn issue show <ref>\` before editing GitHub issue state. Prefer
\`dn issue comment\` for append-only progress updates, and use \`dn issue edit\`
only when the user explicitly wants the issue body or metadata changed.
`;

const DN_OPENAI_METADATA_CONTENT = `${YAML_MANAGED_MARKER}
name: dn
description: Use dn for GitHub issues, kickstart workflows, plan files, VCS sync, and project velocity workflows.
`;

const CURSOR_IDE_SECTION = `
## Cursor IDE

You are the outer harness. Kickstart is a CLI command, not a Cursor
Task/subagent.

- When the user names an issue, a plan file, or \`kickstart\` / \`meld\` /
  \`loop\` / \`land\`: orchestrate the CLI. Do not reimplement the ticket in-chat.
- A pasted GitHub issue URL plus kickstart: resolve argv (full URL,
  \`--allow-cross-repo\` on repo mismatch, \`--steer\` / \`--context-file\` from the
  message). Do not quiz for other flags.
- When they iterate on code in this session: implement here.
- After a local (\`none\`) run, ask whether to commit. If yes, you write the
  commit. Do not auto-run \`dn land\`. After \`--publish pr\` or
  \`--publish direct\`, report the PR or branch instead.
- Do not pass \`--agent cursor\` unless asked. Let project config / \`DN_AGENT\`
  pick the nested harness.
- Plan mode maps to \`dn meld\` (do not implement). After the plan is accepted,
  \`dn loop\`, then ask before committing.
`;

function withCursorIdeSection(skillMarkdown: string): string {
  return `${skillMarkdown.trimEnd()}\n${CURSOR_IDE_SECTION}`;
}

const BASE_IMAGE_SKILL_CONTENT = `---
name: base-image
description: Use when configuring dn Docker sandbox golden images, choosing or customizing a project base image / Dockerfile, or setting sandbox.docker.image and sandbox.docker.dockerfile in .github/dn/config.json.
---

${MARKDOWN_MANAGED_MARKER}

# Project base image (golden image)

Maintain a **golden image** for agent sandbox environments: a reproducible
container with Deno, \`dn\`, an agent harness, and \`git\`. Point dn at the image
from config; fork a Dockerfile when the project needs extra toolchains.

## Config

In \`.github/dn/config.json\` (schema \`1.1\`), under \`sandbox.docker\`:

| Field        | Purpose                                                              |
| ------------ | -------------------------------------------------------------------- |
| \`image\`      | Runtime image pull ref (required for Docker sandbox)                 |
| \`dockerfile\` | Optional repo-relative path to the Dockerfile that builds that image |

\`dockerfile\` is declarative only — dn does **not** build at provision time.
Build and push yourself (or in CI), then set \`image\` to the published tag or
digest.

Example:

\`\`\`json
{
  "schema_version": "1.1",
  "agent": "opencode",
  "sandbox": {
    "provider": "docker",
    "docker": {
      "image": "ghcr.io/OWNER/project:sha-abc1234",
      "dockerfile": "Dockerfile",
      "network": "bridge",
      "read_only_root": true,
      "env_pass_through": [
        "OPENAI_API_KEY",
        "ANTHROPIC_API_KEY",
        "CURSOR_API_KEY"
      ]
    }
  }
}
\`\`\`

## Image contract

The image must include:

- **Deno** runtime (≥ 2.6.3)
- **dn** CLI (precompiled or from the workspace)
- **Agent harness** (opencode, cursor, claude, codex, or copilot)
- **git**, plus a shell (\`bash\`) for agent commands

Canonical images are published from
[chesapeakedev/dn-images](https://github.com/chesapeakedev/dn-images) as
\`ghcr.io/chesapeakedev/dn:<harness>\`. Version and source tags include the
harness suffix, such as \`:0.1.0-codex\` and \`:sha-abc123def456-codex\`.

## Hygiene (do this)

- Pin \`FROM\` by **digest** (\`image@sha256:…\`); keep the human tag in a comment
- Pin tool versions (\`OPENCODE_VERSION\`, Deno base, language runtimes)
- Prefer **\`:sha-*\` or digest** in \`sandbox.docker.image\` for CI
- Run as a **non-root** \`USER\` when mounts stay writable
- **Never bake secrets**; use \`env_pass_through\` / runtime env
- Keep \`network\` default \`none\`; use \`bridge\` only for outbound APIs
- Prefer \`read_only_root: true\` with a writable workspace mount
- Stay on **Debian-family** bases (\`denoland/deno:debian-*\`); not distroless
- Do **not** mount the Docker socket or full \`~/.ssh\`
- Prefer \`exe.dev\` for stronger isolation than a fatter Docker image

## Useful base-image suggestions

1. **dn (default)** — use the canonical tag matching the selected harness
2. **VCS overlay** — add Sapling (\`sl\`) when the repo uses Sapling
3. **Language overlays** — Node/npm, Python (uv/pip), or Rust/\`cargo\` in a fork
4. **Harness variants** — one primary harness per image
5. **Pinned prod config** — \`:sha-<commit>\` or digest + \`dockerfile\` path
6. **When not to customize** — skip if provider is \`none\`

## STOP conditions

- Do not bake API keys, tokens, or SSH private keys into the image
- Do not recommend distroless/static images as the agent sandbox base
- Do not mount the host Docker socket into the sandbox
`;

const BASE_IMAGE_OPENAI_METADATA_CONTENT = `${YAML_MANAGED_MARKER}
name: base-image
description: Configure dn Docker sandbox golden images, Dockerfiles, and sandbox.docker image settings.
`;

const RFC_SKILL_CONTENT = `---
name: rfc
description: Use when turning a greenfield idea into an initial RFC set, writing RFCs, or designing a system. Guides interview → overview → ordered RFC proposals → dn rfc writes. Do NOT implement product code.
---

${MARKDOWN_MANAGED_MARKER}

# RFC authoring

Turn a greenfield idea or design question into a durable **5–15 RFC corpus** in
\`rfcs/\`. RFCs capture **why** and **how**; use \`plans/\` only for single-issue
execution.

## Triggers

Use this skill when the user asks to:

- design a system or architecture from scratch
- write RFCs or a design doc corpus
- bootstrap durable design decisions before implementation

## Workflow

1. **Interview** — clarify goal, boundaries, constraints, and non-goals
2. **Initialize** — run \`dn rfc init\` if \`rfcs/\` is missing
3. **Overview** — draft or refine \`000-overview.md\` (scope, glossary, RFC index)
4. **Propose** — list 5–15 ordered RFC titles with one-line rationale each
5. **Write** — create each RFC with \`dn rfc create\` and fill decision-focused bodies
6. **Review** — set statuses to \`review\` (or leave \`draft\`) for human review

## \`dn rfc\` commands

\`\`\`bash
dn rfc init
dn rfc create --title "Descriptive Title" [--slug custom-slug] [--github-issue URL]
dn rfc list [--status draft|review|accepted|implementing|done|superseded] [--json]
dn rfc show <id|slug|path>
dn rfc status <id|slug|path> <status>
dn rfc complete <id>    # shortcut for status done
\`\`\`

Status flow: \`draft\` → \`review\` → \`accepted\` → \`implementing\` → \`done\` (or
\`superseded\`).

Install this skill:

\`\`\`bash
dn init agents --skill rfc --agent opencode
\`\`\`

First-run project setup (optional):

\`\`\`bash
dn init wizard --project
\`\`\`

## STOP conditions

- **Do not implement product code** — RFC authoring only
- **Do not invent a parallel tracker** — use \`dn rfc\` and \`rfcs/\`, not ad-hoc docs
- **Keep RFCs short and decision-focused** — prefer bullets over essays
- **Do not overwrite human-edited RFCs** without explicit approval
- Leave statuses at \`draft\` or \`review\` unless the user asks to accept

## Related

- Default dn skill — consult \`dn rfc list\` / read \`rfcs/\` before large design work
- \`plans/\` — execution plans for GitHub issues, not durable design
`;

const RFC_OPENAI_METADATA_CONTENT = `${YAML_MANAGED_MARKER}
name: rfc
description: Bootstrap a durable RFC corpus with dn rfc for greenfield design work.
`;

const INSTALLABLE_SKILLS: Record<SkillName, InstallableSkill> = {
  dn: {
    name: "dn",
    skillMarkdown: DN_SKILL_CONTENT,
    openAiMetadata: DN_OPENAI_METADATA_CONTENT,
  },
  "base-image": {
    name: "base-image",
    skillMarkdown: BASE_IMAGE_SKILL_CONTENT,
    openAiMetadata: BASE_IMAGE_OPENAI_METADATA_CONTENT,
  },
  rfc: {
    name: "rfc",
    skillMarkdown: RFC_SKILL_CONTENT,
    openAiMetadata: RFC_OPENAI_METADATA_CONTENT,
  },
};

interface AgentsMdStructure {
  sections: Array<{
    name: string;
    level: number;
    content: string;
    startLine: number;
    endLine: number;
  }>;
  hasProjectOverview: boolean;
  hasBuildLintTest: boolean;
  hasDnSection: boolean;
  hasCursorRules: boolean;
  customSections: string[];
  rawContent: string;
}

function parseAgentsMd(content: string): AgentsMdStructure {
  const lines = content.split("\n");
  const sections: AgentsMdStructure["sections"] = [];
  let currentSection: {
    name: string;
    level: number;
    content: string;
    startLine: number;
    endLine: number;
  } | null = null;

  const standardSectionNames = [
    "Project Overview",
    "Build",
    "Linting",
    "Testing",
    "Imports",
    "Formatting",
    "TypeScript",
    "Naming",
    "Module",
    "Error",
    "Async",
    "Testing Guidelines",
    "Git",
    "Cursor",
    "Agent Expectations",
    "Using dn",
    "Using Kickstart",
    "Kickstart",
  ];

  let hasProjectOverview = false;
  let hasBuildLintTest = false;
  let hasDnSection = false;
  let hasCursorRules = false;
  const customSections: string[] = [];
  let activeFenceMarker: "```" | "~~~" | null = null;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmedLine = line.trimStart();
    const fenceMatch = trimmedLine.match(/^(```|~~~)/);
    const headerMatch = activeFenceMarker === null
      ? line.match(/^(#{1,6})\s+(.+)$/)
      : null;
    if (headerMatch) {
      if (currentSection) {
        currentSection.endLine = i - 1;
        sections.push(currentSection);
      }

      const level = headerMatch[1].length;
      const name = headerMatch[2].trim();
      const isStandard = standardSectionNames.some((std) => name.includes(std));

      if (name.includes("Project Overview")) {
        hasProjectOverview = true;
      }
      if (
        name.includes("Build") || name.includes("Linting") ||
        name.includes("Testing")
      ) {
        hasBuildLintTest = true;
      }
      if (name.includes("Using dn") || name.includes("Kickstart")) {
        hasDnSection = true;
      }
      if (name.includes("Cursor") || name.includes("Copilot")) {
        hasCursorRules = true;
      }

      if (!isStandard) {
        customSections.push(name);
      }

      currentSection = {
        name,
        level,
        content: line + "\n",
        startLine: i,
        endLine: i,
      };
    } else if (currentSection) {
      currentSection.content += line + "\n";
    }

    if (fenceMatch) {
      const fenceMarker = fenceMatch[1] as "```" | "~~~";
      if (activeFenceMarker === fenceMarker) {
        activeFenceMarker = null;
      } else if (activeFenceMarker === null) {
        activeFenceMarker = fenceMarker;
      }
    }
  }

  if (currentSection) {
    currentSection.endLine = lines.length - 1;
    sections.push(currentSection);
  }

  return {
    sections,
    hasProjectOverview,
    hasBuildLintTest,
    hasDnSection,
    hasCursorRules,
    customSections,
    rawContent: content,
  };
}

function hasDnSection(content: string): boolean {
  const structure = parseAgentsMd(content);
  if (!structure.hasDnSection) {
    return false;
  }

  const dnSection = structure.sections.find((s) =>
    s.name.includes("Using dn") || s.name.includes("Kickstart")
  );

  return dnSection !== undefined;
}

function genDnSection(): string {
  return `## Using dn

Use \`dn\` as the primary interface for this repo's GitHub workflows and plan
artifacts. Prefer it over ad-hoc scripts or direct API calls when reading
issues, updating GitHub state, preparing plans, or processing review feedback.

Read repository \`dn.json\` at the start of a session. If \`harness_hints\` is
present, honor those string notes for this checkout.

### GitHub access

Use \`dn issue\` for authenticated access to repository issues, including private
repositories that the signed-in user can access. Prefer it when an agent needs
to inspect or update issue state from the terminal.

\`\`\`bash
dn issue list --label bug
dn issue show 123
dn issue show 123 --json
dn issue comment 123 --body-file update.md
dn issue edit 123 --add-label needs-triage
dn issue create --title "Brief title" --body-file description.md
dn issue create --repo owner/repo --title "Brief title" --body-file description.md
dn issue relationship list 123
\`\`\`

Guidelines:

- Use \`dn issue show <ref>\` before making issue edits so updates are based on
  current state.
- Prefer \`dn issue comment\` for append-only progress updates and refined
  understanding.
- Use \`dn issue edit\` only when the user explicitly wants the issue body or
  metadata changed.
- Use \`--repo owner/repo\` when the target issue or new issue belongs to a
  repository other than the current checkout.
- Use \`--json\` when structured output is useful for follow-up agent steps.
- Issue references may be \`123\`, \`#123\`, or a full GitHub issue URL.

When writing issue content, prefer concise structured Markdown:

\`\`\`md
## Summary
- ...

## Updated understanding
- ...

## Proposed next steps
- ...

## Open questions / risks
- ...
\`\`\`

### Repeatable flows

Default publish mode is local (\`none\`). Do not stack another kickstart on
uncommitted kickstart work.

When this AGENTS.md is used from an **IDE chat**, implement with the CLI, then
ask whether to commit after a local (\`none\`) run. If the user says yes, the IDE
agent writes the commit and omits \`*.plan.md\`. Do not auto-run \`dn land\`.

If the user asks to open/create a PR (or says \`--awp\` / \`--publish pr\`), pass
\`--publish pr\` and report the PR URL. If they ask for \`--publish direct\` (or
push to trunk as part of kickstart), pass \`--publish direct\` and report the
branch. Do not also commit in the IDE after those modes. If they say "publish"
with no PR vs direct, ask which.

\`dn land\` is for attended CLI, CI, and denoise. \`dn sync\` publishes to trunk.

\`\`\`bash
dn kickstart <issue-url-or-number>         # Full plan + implement
dn kickstart --publish pr <issue-url>      # Branch, commit, open a PR
dn kickstart --publish direct <issue-url>  # Commit and push to default branch
dn meld <issue-url-or-number>              # Plan phase
dn loop plans/task.plan.md                 # Implement from an existing plan
dn land plans/task.plan.md                 # CLI/CI close-out into VCS commits
dn land --single plans/task.plan.md        # One deterministic commit, no agent
dn fixup <pull-request-url>                # Address PR review feedback
dn meld a.md b.md --plan-name merged       # Plan from combined sources
\`\`\`

Use \`dn kickstart\` when the user wants the whole issue implemented. A pasted
GitHub issue URL: pass the full URL; add \`--allow-cross-repo\` when
\`owner/repo\` is not this workspace; put extra chat guidance in \`--steer\`.
Use \`dn meld\` → \`dn loop\` when planning and implementation should be reviewed
between phases. Use \`dn fixup\` when the task is to address existing PR comments
rather than re-implement from scratch.

### Milestones, queues, and context

\`\`\`bash
dn init stack 42
dn kickstart --milestone 42
dn todo done 123
dn tidy
dn context check cli/main.ts
\`\`\`

- Use \`dn init stack\` and milestone-aware \`dn kickstart\` for ordered work from
  a GitHub milestone.
- Use \`dn todo done\` and \`dn tidy\` to manage the local prioritized task list
  in \`~/.dn/todo.md\`.
- Use \`dn context check\` to inspect inherited \`AGENTS.md\` context and prompt
  size when context assembly is relevant.

### Authentication

If GitHub operations fail due to missing auth, prefer existing cached auth. If
setup is needed, use:

\`\`\`bash
dn auth
\`\`\`
`;
}

function mergeAgentsMd(baseContent: string): string {
  const structure = parseAgentsMd(baseContent);
  const kickstartSection = genDnSection();
  let result = baseContent;

  if (structure.hasCursorRules) {
    const cursorSection = structure.sections.find((s) =>
      s.name.includes("Cursor") || s.name.includes("Copilot")
    );
    if (cursorSection) {
      const sectionContent = cursorSection.content.toLowerCase();
      if (!sectionContent.includes("kickstart")) {
        const lines = result.split("\n");
        const sectionEndLine = cursorSection.endLine;
        let insertLine = sectionEndLine;
        for (let i = cursorSection.startLine; i <= sectionEndLine; i++) {
          if (lines[i].trim() === "" && i > cursorSection.startLine + 2) {
            insertLine = i;
            break;
          }
        }
        const beforeRule = lines.slice(0, insertLine).join("\n");
        const afterRule = lines.slice(insertLine).join("\n");
        const kickstartRule =
          "- If `.cursor/skills/dn/SKILL.md` exists, follow the dn skill for kickstart / meld / loop; ask before committing.";
        result = beforeRule + "\n" + kickstartRule + "\n" + afterRule;
      }
    }
  }

  if (hasDnSection(result)) {
    return result;
  }

  const updatedStructure = parseAgentsMd(result);
  let insertIndex = -1;

  const preferredInsertAfter = [
    "Agent Expectations",
    "Cursor",
    "Copilot",
    "Git",
    "Testing Guidelines",
  ];

  for (let i = updatedStructure.sections.length - 1; i >= 0; i--) {
    const section = updatedStructure.sections[i];
    if (
      preferredInsertAfter.some((name) => section.name.includes(name))
    ) {
      insertIndex = section.endLine + 1;
      break;
    }
  }

  if (insertIndex === -1 && updatedStructure.customSections.length > 0) {
    const firstCustomIndex = updatedStructure.sections.findIndex((s) =>
      updatedStructure.customSections.includes(s.name)
    );
    if (firstCustomIndex !== -1) {
      insertIndex = updatedStructure.sections[firstCustomIndex].startLine;
    }
  }

  if (insertIndex === -1) {
    const lines = result.split("\n");
    while (lines.length > 0 && lines[lines.length - 1].trim() === "") {
      lines.pop();
    }
    return lines.join("\n") + "\n\n" + kickstartSection;
  }

  const lines = result.split("\n");
  const before = lines.slice(0, insertIndex).join("\n");
  const after = lines.slice(insertIndex).join("\n");

  const spacing = after.trim().startsWith("#") ? "\n\n" : "\n";
  return before + spacing + kickstartSection + spacing + after;
}

function isMinimalAgentsMd(content: string): boolean {
  const trimmed = content.trim();
  if (trimmed.length < 500) {
    return true;
  }

  const structure = parseAgentsMd(content);
  if (structure.sections.length < 3) {
    return true;
  }

  if (!structure.hasProjectOverview && !structure.hasBuildLintTest) {
    return true;
  }

  return false;
}

function generateMinimalTemplate(): string {
  return `# AGENTS.md

This file provides instructions for agentic coding agents operating in this repository.

${genDnSection()}`;
}

function isSkillAgent(value: string): value is SkillAgent {
  return SUPPORTED_SKILL_AGENTS.some((agent) => agent === value);
}

function isSkillName(value: string): value is SkillName {
  return SUPPORTED_SKILL_NAMES.some((name) => name === value);
}

function fail(message: string): never {
  console.error(message);
  Deno.exit(1);
}

function parseInitAgentsOptions(args: string[]): InitAgentsOptions {
  const options: InitAgentsOptions = {
    skill: false,
    skillName: "dn",
    scope: "repo",
    dryRun: false,
    json: false,
    force: false,
  };

  for (let index = 0; index < args.length; index++) {
    const arg = args[index];

    if (arg === "--skill") {
      options.skill = true;
      const next = args[index + 1];
      if (next && !next.startsWith("-")) {
        if (!isSkillName(next)) {
          fail(
            `Unsupported skill name "${next}". Expected one of: ${
              SUPPORTED_SKILL_NAMES.join(", ")
            }`,
          );
        }
        options.skillName = next;
        index++;
      }
    } else if (arg === "--agent") {
      const value = args[index + 1];
      if (!value || value.startsWith("-")) {
        fail("--agent requires one of: codex, claude, opencode, cursor");
      }
      if (!isSkillAgent(value)) {
        fail(`Unsupported agent for --skill: ${value}`);
      }
      options.agent = value;
      index++;
    } else if (arg === "--scope") {
      const value = args[index + 1];
      if (value !== "repo" && value !== "user") {
        fail("--scope requires one of: repo, user");
      }
      options.scope = value;
      index++;
    } else if (arg === "--dry-run") {
      options.dryRun = true;
    } else if (arg === "--json") {
      options.json = true;
    } else if (arg === "--force") {
      options.force = true;
    } else if (arg.startsWith("-")) {
      fail(`Unknown option: ${arg}`);
    } else {
      fail(`Unexpected argument: ${arg}`);
    }
  }

  return options;
}

function getHomeDirectory(): string {
  const home = Deno.env.get("DN_INIT_AGENTS_HOME") ?? Deno.env.get("HOME") ??
    Deno.env.get("USERPROFILE");
  if (!home) {
    fail("Unable to resolve home directory for --scope user");
  }
  return home;
}

function skillBaseDirectory(
  workspaceRoot: string,
  agent: SkillAgent,
  scope: SkillScope,
  skillName: SkillName,
): string {
  if (scope === "repo") {
    if (agent === "claude") {
      return join(workspaceRoot, ".claude", "skills", skillName);
    }
    if (agent === "cursor") {
      return join(workspaceRoot, ".cursor", "skills", "dn");
    }
    return join(workspaceRoot, ".agents", "skills", skillName);
  }

  const home = getHomeDirectory();
  if (agent === "claude") {
    return join(home, ".claude", "skills", skillName);
  }
  if (agent === "cursor") {
    return join(home, ".cursor", "skills", "dn");
  }
  return join(home, ".agents", "skills", skillName);
}

function buildSkillTargets(
  workspaceRoot: string,
  agent: SkillAgent,
  scope: SkillScope,
  skillName: SkillName,
): SkillTarget[] {
  const skill = INSTALLABLE_SKILLS[skillName];
  const baseDirectory = skillBaseDirectory(
    workspaceRoot,
    agent,
    scope,
    skillName,
  );

  if (agent === "cursor") {
    return [{
      path: join(baseDirectory, "SKILL.md"),
      content: withCursorIdeSection(skill.skillMarkdown),
    }];
  }

  const targets: SkillTarget[] = [{
    path: join(baseDirectory, "SKILL.md"),
    content: skill.skillMarkdown,
  }];

  if (agent === "codex" || agent === "opencode") {
    targets.push({
      path: join(baseDirectory, "agents", "openai.yaml"),
      content: skill.openAiMetadata,
    });
  }

  return targets;
}

async function fileExists(path: string): Promise<boolean> {
  try {
    const stat = await Deno.stat(path);
    return stat.isFile;
  } catch {
    return false;
  }
}

async function planSkillTarget(target: SkillTarget): Promise<InstallResult> {
  if (!await fileExists(target.path)) {
    return {
      path: target.path,
      status: "write",
      reason: "missing",
    };
  }

  const existingContent = await Deno.readTextFile(target.path);
  if (existingContent === target.content) {
    return {
      path: target.path,
      status: "skip",
      reason: "current",
    };
  }

  if (existingContent.includes(GENERATED_MARKER)) {
    return {
      path: target.path,
      status: "write",
      reason: "managed-outdated",
    };
  }

  return {
    path: target.path,
    status: "conflict",
    reason: "existing-unmanaged-file",
  };
}

async function installSkillTargets(
  targets: SkillTarget[],
  options: InitAgentsOptions,
): Promise<InstallResult[]> {
  const plannedResults = await Promise.all(targets.map(planSkillTarget));
  const conflicts = plannedResults.filter((result) =>
    result.status === "conflict"
  );

  if (conflicts.length > 0 && !options.force && !options.dryRun) {
    const files = conflicts.map((result) => `  - ${result.path}`).join("\n");
    fail(
      `Refusing to overwrite unmanaged skill file(s). Re-run with --force to replace them.\n${files}`,
    );
  }

  if (options.dryRun) {
    return plannedResults;
  }

  const results: InstallResult[] = [];
  for (const target of targets) {
    const plannedResult = plannedResults.find((result) =>
      result.path === target.path
    );
    if (!plannedResult) {
      throw new Error(`Missing planned result for ${target.path}`);
    }

    if (plannedResult.status === "skip") {
      results.push(plannedResult);
      continue;
    }

    await Deno.mkdir(dirname(target.path), { recursive: true });
    await Deno.writeTextFile(target.path, target.content);
    results.push({
      path: target.path,
      status: "write",
      reason: plannedResult.status === "conflict"
        ? "forced"
        : plannedResult.reason,
    });
  }

  return results;
}

function printSkillInstallResults(
  results: InstallResult[],
  options: InitAgentsOptions,
): void {
  if (options.json) {
    console.log(JSON.stringify({ results }, null, 2));
    return;
  }

  for (const result of results) {
    const prefix = options.dryRun ? "Would" : "Did";
    if (result.status === "write") {
      console.log(`${prefix} write ${result.path}`);
    } else if (result.status === "skip") {
      console.log(`Skipped ${result.path} (already current)`);
    } else {
      console.log(`Conflict ${result.path} (${result.reason})`);
    }
  }
}

async function handleInitAgentsSkill(
  workspaceRoot: string,
  options: InitAgentsOptions,
): Promise<void> {
  if (!options.agent) {
    fail(
      "dn init agents --skill requires --agent <codex|claude|opencode|cursor>\n\nExamples:\n  dn init agents --skill --agent codex\n  dn init agents --skill base-image --agent opencode\n  dn init agents --skill rfc --agent opencode\n  dn init agents --skill --agent claude\n  dn init agents --skill --agent cursor",
    );
  }

  if (options.agent === "cursor" && options.skillName !== "dn") {
    fail(
      `Cursor skill installation only supports the dn harness skill.\n` +
        `It writes .cursor/skills/dn/SKILL.md (or ~/.cursor/skills/dn/ with --scope user).\n` +
        `Install ${options.skillName} with: dn init agents --skill ${options.skillName} --agent opencode`,
    );
  }

  const targets = buildSkillTargets(
    workspaceRoot,
    options.agent,
    options.scope,
    options.skillName,
  );
  const results = await installSkillTargets(targets, options);
  printSkillInstallResults(results, options);
}

export async function handleInitAgents(args: string[]): Promise<void> {
  const workspaceRoot = Deno.cwd();

  const showHelp = args.includes("--help") || args.includes("-h");

  if (showHelp) {
    console.log(
      "dn init agents - Update AGENTS.md or install dn agent skill\n",
    );
    console.log("Usage:");
    console.log("  dn init agents\n");
    console.log(
      "  dn init agents --skill [name] --agent <agent> [options]\n",
    );
    console.log("Description:");
    console.log(
      "  Updates the AGENTS.md file in the current directory with instructions",
    );
    console.log(
      "  for using dn CLI. If AGENTS.md doesn't exist, creates it.",
    );
    console.log(
      "  With --skill, installs a named skill for one selected agent.",
    );
    console.log(
      "  Cursor only installs the dn skill (harness plug-in).",
    );
    console.log(
      `  Skill names: ${SUPPORTED_SKILL_NAMES.join(", ")} (default: dn).\n`,
    );
    console.log("Options:");
    console.log(
      "  --skill [name]          Install skill files (default name: dn)",
    );
    console.log(
      "  --agent <agent>         Required with --skill: codex, claude, opencode, cursor",
    );
    console.log("  --scope <repo|user>     Install scope (default: repo)");
    console.log("  --dry-run               Report changes without writing");
    console.log("  --json                  Emit JSON output for --skill");
    console.log(
      "  --force                 Replace conflicting unmanaged files",
    );
    console.log("  --help, -h              Show this help message\n");
    console.log("Examples:");
    console.log("  dn init agents");
    console.log("  dn init agents --skill --agent codex");
    console.log("  dn init agents --skill base-image --agent opencode");
    console.log("  dn init agents --skill rfc --agent opencode");
    console.log("  dn init agents --skill --agent cursor");
    console.log("  dn init agents --skill --agent cursor --scope user");
    console.log("  dn init agents --skill --agent claude --dry-run --json");
    Deno.exit(0);
  }

  const options = parseInitAgentsOptions(args);

  if (options.skill) {
    await handleInitAgentsSkill(workspaceRoot, options);
    return;
  }

  const agentsMdPath = join(workspaceRoot, "AGENTS.md");

  let existingContent: string | undefined;
  let wasNewFile = false;

  try {
    existingContent = await Deno.readTextFile(agentsMdPath);
  } catch {
    wasNewFile = true;
  }

  let newContent: string;

  if (!existingContent || isMinimalAgentsMd(existingContent)) {
    newContent = generateMinimalTemplate();
  } else {
    newContent = mergeAgentsMd(existingContent);
  }

  await Deno.writeTextFile(agentsMdPath, newContent);

  if (wasNewFile) {
    console.log(`Created ${agentsMdPath} with dn instructions`);
  } else {
    console.log(`Updated ${agentsMdPath} with dn instructions`);
  }
}
