// Copyright 2026 Chesapeake Computing
// SPDX-License-Identifier: Apache-2.0

import { dirname, join } from "@std/path";

type SkillAgent = "codex" | "claude" | "opencode" | "cursor";
type SkillScope = "repo" | "user";
type InstallStatus = "write" | "skip" | "conflict";

interface InitAgentsOptions {
  skill: boolean;
  agent?: SkillAgent;
  scope: SkillScope;
  dryRun: boolean;
  json: boolean;
  force: boolean;
}

interface SkillTarget {
  path: string;
  content: string;
}

interface InstallResult {
  path: string;
  status: InstallStatus;
  reason: string;
}

const SUPPORTED_SKILL_AGENTS = [
  "codex",
  "claude",
  "opencode",
  "cursor",
] as const;
const GENERATED_MARKER = "Generated by dn init agents --skill";
const MARKDOWN_MANAGED_MARKER = `<!-- ${GENERATED_MARKER}. -->`;
const YAML_MANAGED_MARKER = `# ${GENERATED_MARKER}.`;

const DN_SKILL_CONTENT = `---
name: dn
description: Use when interacting with the dn CLI for GitHub issues, kickstart workflows, VCS sync, project velocity, and agent-backed plan execution.
---

${MARKDOWN_MANAGED_MARKER}

# dn

\`dn\` is a Deno-based CLI for GitHub issue-driven development workflows. It is
the primary interface to this repository's workflows. Prefer it over ad-hoc
scripts or direct API calls when preparing workspaces, iterating on plans, or
coordinating changes.

## Quickstart

\`\`\`bash
dn                    # list subcommands
dn <subcommand> -h    # help for a specific subcommand
\`\`\`

## Global Flags

| Flag                    | Effect                                                           |
| ----------------------- | ---------------------------------------------------------------- |
| \`--agent <name>\`        | Agent harness: \`opencode\` (default), \`cursor\`, \`claude\`, \`codex\` |
| \`--opencode\`            | Alias for \`--agent opencode\`                                     |
| \`--cursor\` / \`-c\`       | Alias for \`--agent cursor\`                                       |
| \`--claude\`              | Alias for \`--agent claude\`                                       |
| \`--codex\`               | Alias for \`--agent codex\`                                        |
| \`--unattended\` / \`--ci\` | Non-interactive output                                             |
| \`--no-color\`            | Disable ANSI color                                                 |
| \`--color\`               | Force ANSI color even on non-TTY                                   |
| \`--json\`                | JSON output where supported                                        |

### Agent harness selection priority

1. Explicit \`--agent <name>\` global flag
2. Legacy per-command flag: \`--cursor\`, \`--claude\`, \`--codex\`, or \`--opencode\`
3. Environment toggle: \`CURSOR_ENABLED=1\`, \`CLAUDE_ENABLED=1\`, or \`CODEX_ENABLED=1\`
4. Default: OpenCode

## Token resolution order

1. \`GITHUB_TOKEN\` or \`DANGEROUS_GITHUB_TOKEN\` environment variable
2. \`dn auth\` cached device-flow token in \`~/.dn/\`
3. \`gh auth token\`

## Common environment variables

- \`ISSUE\` - fallback issue URL or number for \`kickstart\` and \`prep\`
- \`WORKSPACE_ROOT\` - project root directory
- \`GITHUB_TOKEN\` - GitHub personal access token
- \`PR_URL\` - PR URL for \`fixup\`
- \`PLAN\` - path to plan file for \`loop\`

## Common workflows

\`\`\`bash
dn kickstart <issue-url-or-number>         # Full plan + implement workflow
dn prep <issue-url-or-number>              # Plan phase only
dn loop --plan-file plans/task.plan.md     # Implement from an existing plan
dn fixup <pull-request-url>                # Address PR review feedback
dn meld a.md b.md --plan-name merged       # Merge sources, then run prep
dn init stack 42                           # Create a milestone task stack
dn sync                                    # Git/Sapling lint, rebase, publish
\`\`\`

Use \`dn issue show <ref>\` before editing GitHub issue state. Prefer
\`dn issue comment\` for append-only progress updates, and use \`dn issue edit\`
only when the user explicitly wants the issue body or metadata changed.
`;

const OPENAI_METADATA_CONTENT = `${YAML_MANAGED_MARKER}
name: dn
description: Use dn for GitHub issues, kickstart workflows, plan files, VCS sync, and project velocity workflows.
`;

const CURSOR_RULE_CONTENT = `---
description: Use dn for GitHub issues, kickstart workflows, plan files, VCS sync, and project velocity workflows.
globs:
  - "**/*"
alwaysApply: false
---

${MARKDOWN_MANAGED_MARKER}

# dn

Use \`dn\` as the primary interface for GitHub issue-driven workflows, plan
files, and agent-backed implementation loops in this repository.

Prefer these commands over ad-hoc GitHub scripts:

\`\`\`bash
dn issue show <ref>
dn issue comment <ref> --body-file update.md
dn prep <issue-url-or-number>
dn loop --plan-file plans/task.plan.md
dn kickstart <issue-url-or-number>
dn fixup <pull-request-url>
dn sync
\`\`\`

Follow the canonical dn skill behavior from \`.agents/skills/dn/SKILL.md\` when
that file is present.
`;

interface AgentsMdStructure {
  sections: Array<{
    name: string;
    level: number;
    content: string;
    startLine: number;
    endLine: number;
  }>;
  hasProjectOverview: boolean;
  hasBuildLintTest: boolean;
  hasDnSection: boolean;
  hasCursorRules: boolean;
  customSections: string[];
  rawContent: string;
}

function parseAgentsMd(content: string): AgentsMdStructure {
  const lines = content.split("\n");
  const sections: AgentsMdStructure["sections"] = [];
  let currentSection: {
    name: string;
    level: number;
    content: string;
    startLine: number;
    endLine: number;
  } | null = null;

  const standardSectionNames = [
    "Project Overview",
    "Build",
    "Linting",
    "Testing",
    "Imports",
    "Formatting",
    "TypeScript",
    "Naming",
    "Module",
    "Error",
    "Async",
    "Testing Guidelines",
    "Git",
    "Cursor",
    "Agent Expectations",
    "Using dn",
    "Using Kickstart",
    "Kickstart",
  ];

  let hasProjectOverview = false;
  let hasBuildLintTest = false;
  let hasDnSection = false;
  let hasCursorRules = false;
  const customSections: string[] = [];
  let activeFenceMarker: "```" | "~~~" | null = null;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmedLine = line.trimStart();
    const fenceMatch = trimmedLine.match(/^(```|~~~)/);
    const headerMatch = activeFenceMarker === null
      ? line.match(/^(#{1,6})\s+(.+)$/)
      : null;
    if (headerMatch) {
      if (currentSection) {
        currentSection.endLine = i - 1;
        sections.push(currentSection);
      }

      const level = headerMatch[1].length;
      const name = headerMatch[2].trim();
      const isStandard = standardSectionNames.some((std) => name.includes(std));

      if (name.includes("Project Overview")) {
        hasProjectOverview = true;
      }
      if (
        name.includes("Build") || name.includes("Linting") ||
        name.includes("Testing")
      ) {
        hasBuildLintTest = true;
      }
      if (name.includes("Using dn") || name.includes("Kickstart")) {
        hasDnSection = true;
      }
      if (name.includes("Cursor") || name.includes("Copilot")) {
        hasCursorRules = true;
      }

      if (!isStandard) {
        customSections.push(name);
      }

      currentSection = {
        name,
        level,
        content: line + "\n",
        startLine: i,
        endLine: i,
      };
    } else if (currentSection) {
      currentSection.content += line + "\n";
    }

    if (fenceMatch) {
      const fenceMarker = fenceMatch[1] as "```" | "~~~";
      if (activeFenceMarker === fenceMarker) {
        activeFenceMarker = null;
      } else if (activeFenceMarker === null) {
        activeFenceMarker = fenceMarker;
      }
    }
  }

  if (currentSection) {
    currentSection.endLine = lines.length - 1;
    sections.push(currentSection);
  }

  return {
    sections,
    hasProjectOverview,
    hasBuildLintTest,
    hasDnSection,
    hasCursorRules,
    customSections,
    rawContent: content,
  };
}

function hasDnSection(content: string): boolean {
  const structure = parseAgentsMd(content);
  if (!structure.hasDnSection) {
    return false;
  }

  const dnSection = structure.sections.find((s) =>
    s.name.includes("Using dn") || s.name.includes("Kickstart")
  );

  return dnSection !== undefined;
}

function genDnSection(): string {
  return `## Using dn

Use \`dn\` as the primary interface for this repo's GitHub workflows and plan
artifacts. Prefer it over ad-hoc scripts or direct API calls when reading
issues, updating GitHub state, preparing plans, or processing review feedback.

### GitHub access

Use \`dn issue\` for authenticated access to repository issues, including private
repositories that the signed-in user can access. Prefer it when an agent needs
to inspect or update issue state from the terminal.

\`\`\`bash
dn issue list --label bug
dn issue show 123
dn issue show 123 --json
dn issue comment 123 --body-file update.md
dn issue edit 123 --add-label needs-triage
dn issue create --title "Brief title" --body-file description.md
dn issue create --repo owner/repo --title "Brief title" --body-file description.md
dn issue relationship list 123
\`\`\`

Guidelines:

- Use \`dn issue show <ref>\` before making issue edits so updates are based on
  current state.
- Prefer \`dn issue comment\` for append-only progress updates and refined
  understanding.
- Use \`dn issue edit\` only when the user explicitly wants the issue body or
  metadata changed.
- Use \`--repo owner/repo\` when the target issue or new issue belongs to a
  repository other than the current checkout.
- Use \`--json\` when structured output is useful for follow-up agent steps.
- Issue references may be \`123\`, \`#123\`, or a full GitHub issue URL.

When writing issue content, prefer concise structured Markdown:

\`\`\`md
## Summary
- ...

## Updated understanding
- ...

## Proposed next steps
- ...

## Open questions / risks
- ...
\`\`\`

### Workflow commands

Use the command that matches the stage of work:

\`\`\`bash
dn kickstart <issue-url-or-number>         # Full plan + implement workflow
dn prep <issue-url-or-number>              # Plan phase only
dn loop --plan-file plans/task.plan.md     # Implement from an existing plan
dn fixup <pull-request-url>                # Address PR review feedback
dn meld a.md b.md --plan-name merged       # Merge sources, then run prep
\`\`\`

Use \`dn kickstart\` when the user wants the whole issue implemented. Use
\`dn prep\` and \`dn loop\` separately when planning and implementation need to be
split across steps or reviewed between phases. Use \`dn fixup\` when the task is
to address existing PR comments rather than re-implement from scratch.

### Milestones, queues, and context

\`\`\`bash
dn init stack 42
dn kickstart --milestone 42
dn todo done 123
dn tidy
dn context check cli/main.ts
\`\`\`

- Use \`dn init stack\` and milestone-aware \`dn kickstart\` for ordered work from
  a GitHub milestone.
- Use \`dn todo done\` and \`dn tidy\` to manage the local prioritized task list
  in \`~/.dn/todo.md\`.
- Use \`dn context check\` to inspect inherited \`AGENTS.md\` context and prompt
  size when context assembly is relevant.

### Authentication

If GitHub operations fail due to missing auth, prefer existing cached auth. If
setup is needed, use:

\`\`\`bash
dn auth
\`\`\`
`;
}

function mergeAgentsMd(baseContent: string): string {
  const structure = parseAgentsMd(baseContent);
  const kickstartSection = genDnSection();
  let result = baseContent;

  if (structure.hasCursorRules) {
    const cursorSection = structure.sections.find((s) =>
      s.name.includes("Cursor") || s.name.includes("Copilot")
    );
    if (cursorSection) {
      const sectionContent = cursorSection.content.toLowerCase();
      if (!sectionContent.includes("kickstart")) {
        const lines = result.split("\n");
        const sectionEndLine = cursorSection.endLine;
        let insertLine = sectionEndLine;
        for (let i = cursorSection.startLine; i <= sectionEndLine; i++) {
          if (lines[i].trim() === "" && i > cursorSection.startLine + 2) {
            insertLine = i;
            break;
          }
        }
        const beforeRule = lines.slice(0, insertLine).join("\n");
        const afterRule = lines.slice(insertLine).join("\n");
        const kickstartRule =
          "- If \`.cursor/rules/kickstart.mdc\` exists, follow kickstart subagent guidelines.";
        result = beforeRule + "\n" + kickstartRule + "\n" + afterRule;
      }
    }
  }

  if (hasDnSection(result)) {
    return result;
  }

  const updatedStructure = parseAgentsMd(result);
  let insertIndex = -1;

  const preferredInsertAfter = [
    "Agent Expectations",
    "Cursor",
    "Copilot",
    "Git",
    "Testing Guidelines",
  ];

  for (let i = updatedStructure.sections.length - 1; i >= 0; i--) {
    const section = updatedStructure.sections[i];
    if (
      preferredInsertAfter.some((name) => section.name.includes(name))
    ) {
      insertIndex = section.endLine + 1;
      break;
    }
  }

  if (insertIndex === -1 && updatedStructure.customSections.length > 0) {
    const firstCustomIndex = updatedStructure.sections.findIndex((s) =>
      updatedStructure.customSections.includes(s.name)
    );
    if (firstCustomIndex !== -1) {
      insertIndex = updatedStructure.sections[firstCustomIndex].startLine;
    }
  }

  if (insertIndex === -1) {
    const lines = result.split("\n");
    while (lines.length > 0 && lines[lines.length - 1].trim() === "") {
      lines.pop();
    }
    return lines.join("\n") + "\n\n" + kickstartSection;
  }

  const lines = result.split("\n");
  const before = lines.slice(0, insertIndex).join("\n");
  const after = lines.slice(insertIndex).join("\n");

  const spacing = after.trim().startsWith("#") ? "\n\n" : "\n";
  return before + spacing + kickstartSection + spacing + after;
}

function isMinimalAgentsMd(content: string): boolean {
  const trimmed = content.trim();
  if (trimmed.length < 500) {
    return true;
  }

  const structure = parseAgentsMd(content);
  if (structure.sections.length < 3) {
    return true;
  }

  if (!structure.hasProjectOverview && !structure.hasBuildLintTest) {
    return true;
  }

  return false;
}

function generateMinimalTemplate(): string {
  return `# AGENTS.md

This file provides instructions for agentic coding agents operating in this repository.

${genDnSection()}`;
}

function isSkillAgent(value: string): value is SkillAgent {
  return SUPPORTED_SKILL_AGENTS.some((agent) => agent === value);
}

function fail(message: string): never {
  console.error(message);
  Deno.exit(1);
}

function parseInitAgentsOptions(args: string[]): InitAgentsOptions {
  const options: InitAgentsOptions = {
    skill: false,
    scope: "repo",
    dryRun: false,
    json: false,
    force: false,
  };

  for (let index = 0; index < args.length; index++) {
    const arg = args[index];

    if (arg === "--skill") {
      options.skill = true;
    } else if (arg === "--agent") {
      const value = args[index + 1];
      if (!value || value.startsWith("-")) {
        fail("--agent requires one of: codex, claude, opencode, cursor");
      }
      if (!isSkillAgent(value)) {
        fail(`Unsupported agent for --skill: ${value}`);
      }
      options.agent = value;
      index++;
    } else if (arg === "--scope") {
      const value = args[index + 1];
      if (value !== "repo" && value !== "user") {
        fail("--scope requires one of: repo, user");
      }
      options.scope = value;
      index++;
    } else if (arg === "--dry-run") {
      options.dryRun = true;
    } else if (arg === "--json") {
      options.json = true;
    } else if (arg === "--force") {
      options.force = true;
    }
  }

  return options;
}

function getHomeDirectory(): string {
  const home = Deno.env.get("DN_INIT_AGENTS_HOME") ?? Deno.env.get("HOME") ??
    Deno.env.get("USERPROFILE");
  if (!home) {
    fail("Unable to resolve home directory for --scope user");
  }
  return home;
}

function skillBaseDirectory(
  workspaceRoot: string,
  agent: SkillAgent,
  scope: SkillScope,
): string {
  if (scope === "repo") {
    if (agent === "claude") {
      return join(workspaceRoot, ".claude", "skills", "dn");
    }
    if (agent === "cursor") {
      return join(workspaceRoot, ".cursor", "rules");
    }
    return join(workspaceRoot, ".agents", "skills", "dn");
  }

  const home = getHomeDirectory();
  if (agent === "claude") {
    return join(home, ".claude", "skills", "dn");
  }
  return join(home, ".agents", "skills", "dn");
}

function buildSkillTargets(
  workspaceRoot: string,
  agent: SkillAgent,
  scope: SkillScope,
): SkillTarget[] {
  if (scope === "user" && agent === "cursor") {
    fail(
      "Cursor skill installation is repo-scoped. Use: dn init agents --skill --agent cursor --scope repo",
    );
  }

  const baseDirectory = skillBaseDirectory(workspaceRoot, agent, scope);

  if (agent === "cursor") {
    return [{
      path: join(baseDirectory, "dn.mdc"),
      content: CURSOR_RULE_CONTENT,
    }];
  }

  const targets: SkillTarget[] = [{
    path: join(baseDirectory, "SKILL.md"),
    content: DN_SKILL_CONTENT,
  }];

  if (agent === "codex" || agent === "opencode") {
    targets.push({
      path: join(baseDirectory, "agents", "openai.yaml"),
      content: OPENAI_METADATA_CONTENT,
    });
  }

  return targets;
}

async function fileExists(path: string): Promise<boolean> {
  try {
    const stat = await Deno.stat(path);
    return stat.isFile;
  } catch {
    return false;
  }
}

async function planSkillTarget(target: SkillTarget): Promise<InstallResult> {
  if (!await fileExists(target.path)) {
    return {
      path: target.path,
      status: "write",
      reason: "missing",
    };
  }

  const existingContent = await Deno.readTextFile(target.path);
  if (existingContent === target.content) {
    return {
      path: target.path,
      status: "skip",
      reason: "current",
    };
  }

  if (existingContent.includes(GENERATED_MARKER)) {
    return {
      path: target.path,
      status: "write",
      reason: "managed-outdated",
    };
  }

  return {
    path: target.path,
    status: "conflict",
    reason: "existing-unmanaged-file",
  };
}

async function installSkillTargets(
  targets: SkillTarget[],
  options: InitAgentsOptions,
): Promise<InstallResult[]> {
  const plannedResults = await Promise.all(targets.map(planSkillTarget));
  const conflicts = plannedResults.filter((result) =>
    result.status === "conflict"
  );

  if (conflicts.length > 0 && !options.force && !options.dryRun) {
    const files = conflicts.map((result) => `  - ${result.path}`).join("\n");
    fail(
      `Refusing to overwrite unmanaged skill file(s). Re-run with --force to replace them.\n${files}`,
    );
  }

  if (options.dryRun) {
    return plannedResults;
  }

  const results: InstallResult[] = [];
  for (const target of targets) {
    const plannedResult = plannedResults.find((result) =>
      result.path === target.path
    );
    if (!plannedResult) {
      throw new Error(`Missing planned result for ${target.path}`);
    }

    if (plannedResult.status === "skip") {
      results.push(plannedResult);
      continue;
    }

    await Deno.mkdir(dirname(target.path), { recursive: true });
    await Deno.writeTextFile(target.path, target.content);
    results.push({
      path: target.path,
      status: "write",
      reason: plannedResult.status === "conflict"
        ? "forced"
        : plannedResult.reason,
    });
  }

  return results;
}

function printSkillInstallResults(
  results: InstallResult[],
  options: InitAgentsOptions,
): void {
  if (options.json) {
    console.log(JSON.stringify({ results }, null, 2));
    return;
  }

  for (const result of results) {
    const prefix = options.dryRun ? "Would" : "Did";
    if (result.status === "write") {
      console.log(`${prefix} write ${result.path}`);
    } else if (result.status === "skip") {
      console.log(`Skipped ${result.path} (already current)`);
    } else {
      console.log(`Conflict ${result.path} (${result.reason})`);
    }
  }
}

async function handleInitAgentsSkill(
  workspaceRoot: string,
  options: InitAgentsOptions,
): Promise<void> {
  if (!options.agent) {
    fail(
      "dn init agents --skill requires --agent <codex|claude|opencode|cursor>\n\nExamples:\n  dn init agents --skill --agent codex\n  dn init agents --skill --agent claude\n  dn init agents --skill --agent opencode\n  dn init agents --skill --agent cursor",
    );
  }

  const targets = buildSkillTargets(
    workspaceRoot,
    options.agent,
    options.scope,
  );
  const results = await installSkillTargets(targets, options);
  printSkillInstallResults(results, options);
}

export async function handleInitAgents(args: string[]): Promise<void> {
  const workspaceRoot = Deno.cwd();

  const showHelp = args.includes("--help") || args.includes("-h");

  if (showHelp) {
    console.log(
      "dn init agents - Update AGENTS.md or install dn agent skill\n",
    );
    console.log("Usage:");
    console.log("  dn init agents\n");
    console.log("  dn init agents --skill --agent <agent> [options]\n");
    console.log("Description:");
    console.log(
      "  Updates the AGENTS.md file in the current directory with instructions",
    );
    console.log(
      "  for using dn CLI. If AGENTS.md doesn't exist, creates it.",
    );
    console.log(
      "  With --skill, installs native dn skill files for one selected agent.\n",
    );
    console.log("Options:");
    console.log("  --skill                 Install native skill files");
    console.log(
      "  --agent <agent>         Required with --skill: codex, claude, opencode, cursor",
    );
    console.log("  --scope <repo|user>     Install scope (default: repo)");
    console.log("  --dry-run               Report changes without writing");
    console.log("  --json                  Emit JSON output for --skill");
    console.log(
      "  --force                 Replace conflicting unmanaged files",
    );
    console.log("  --help, -h              Show this help message\n");
    console.log("Examples:");
    console.log("  dn init agents");
    console.log("  dn init agents --skill --agent codex");
    console.log("  dn init agents --skill --agent claude --dry-run --json");
    Deno.exit(0);
  }

  const options = parseInitAgentsOptions(args);

  if (options.skill) {
    await handleInitAgentsSkill(workspaceRoot, options);
    return;
  }

  const agentsMdPath = join(workspaceRoot, "AGENTS.md");

  let existingContent: string | undefined;
  let wasNewFile = false;

  try {
    existingContent = await Deno.readTextFile(agentsMdPath);
  } catch {
    wasNewFile = true;
  }

  let newContent: string;

  if (!existingContent || isMinimalAgentsMd(existingContent)) {
    newContent = generateMinimalTemplate();
  } else {
    newContent = mergeAgentsMd(existingContent);
  }

  await Deno.writeTextFile(agentsMdPath, newContent);

  if (wasNewFile) {
    console.log(`Created ${agentsMdPath} with dn instructions`);
  } else {
    console.log(`Updated ${agentsMdPath} with dn instructions`);
  }
}
