// Copyright 2026 Chesapeake Computing
// SPDX-License-Identifier: Apache-2.0

import { assert, assertEquals } from "@std/assert";
import { join } from "@std/path";
import {
  cleanupTestRepo,
  createProjectTestRepo,
  runDnCommand,
} from "./test_utils.ts";

type SkillName = "dn" | "dn-until" | "base-image" | "rfc";
type SkillAgent = "codex" | "claude" | "opencode" | "cursor";

interface InstallCase {
  skill: SkillName;
  agent: SkillAgent;
  relativePath: string;
  metadataPath?: string;
}

const INSTALL_CASES: InstallCase[] = [
  ...(["codex", "claude", "opencode"] as const).flatMap((agent) =>
    (["dn", "dn-until", "base-image", "rfc"] as const).map((skill) => ({
      skill,
      agent,
      relativePath: agent === "claude"
        ? `.claude/skills/${skill}/SKILL.md`
        : agent === "opencode"
        ? `.opencode/skills/${skill}/SKILL.md`
        : `.agents/skills/${skill}/SKILL.md`,
      ...(agent === "claude" ? {} : {
        metadataPath: agent === "opencode"
          ? `.opencode/skills/${skill}/agents/openai.yaml`
          : `.agents/skills/${skill}/agents/openai.yaml`,
      }),
    }))
  ),
  {
    skill: "dn",
    agent: "cursor",
    relativePath: ".cursor/skills/dn/SKILL.md",
  },
];

async function listFiles(root: string, directory = root): Promise<string[]> {
  const files: string[] = [];
  for await (const entry of Deno.readDir(directory)) {
    const path = join(directory, entry.name);
    if (entry.isDirectory) {
      files.push(...await listFiles(root, path));
    } else if (entry.isFile) {
      files.push(path.slice(root.length + 1));
    }
  }
  return files.sort();
}

Deno.test("init agents installs every supported skill artifact in a project repo", async () => {
  const testRepo = await createProjectTestRepo();

  try {
    for (const installCase of INSTALL_CASES) {
      const args = [
        "init",
        "agents",
        "--skill",
        installCase.skill,
        "--agent",
        installCase.agent,
      ];

      const result = await runDnCommand(args, { cwd: testRepo.path });
      assert(result.stdout.includes("Did write"));

      const skillContent = await Deno.readTextFile(
        join(testRepo.path, installCase.relativePath),
      );
      assert(skillContent.includes(`name: ${installCase.skill}`));
      assert(skillContent.includes("Generated by dn init agents --skill"));

      if (installCase.metadataPath) {
        const metadata = await Deno.readTextFile(
          join(testRepo.path, installCase.metadataPath),
        );
        assert(metadata.includes(`name: ${installCase.skill}`));
        assert(metadata.includes("Generated by dn init agents --skill"));
      }

      const repeat = await runDnCommand(args, { cwd: testRepo.path });
      assert(repeat.stdout.includes("Skipped"));
    }

    const expectedFiles = INSTALL_CASES.flatMap((
      { relativePath, metadataPath },
    ) => metadataPath ? [relativePath, metadataPath] : [relativePath]).sort();
    const installedFiles = (await listFiles(testRepo.path)).filter((path) =>
      path.startsWith(".agents/skills/") ||
      path.startsWith(".claude/skills/") ||
      path.startsWith(".cursor/skills/") ||
      path.startsWith(".opencode/skills/")
    );
    assertEquals(installedFiles, expectedFiles);
  } finally {
    await cleanupTestRepo(testRepo);
  }
});
