// Copyright 2026 Chesapeake Computing
// SPDX-License-Identifier: Apache-2.0

import { assert, assertEquals } from "@std/assert";
import { cleanupTestRepo, createTestRepo, runDnCommand } from "./test_utils.ts";

const EXISTING_AGENTS_MD = `# AGENTS.md

## Project Overview

- Runtime: Deno
- Build output: CLI
- Package management: native Deno imports
- Goal: validate init-agents idempotency in a temp repository

## Build

Run the normal project checks before landing changes. Prefer repository tasks over ad hoc commands.

## Testing Guidelines

Tests should be deterministic and isolated. Prefer behavior-focused tests over implementation details. When changing user-visible behavior, add or update tests close to the affected area.

## Custom Notes

Keep diffs small, preserve local conventions, and avoid unrelated refactors.
`;

async function pathExists(path: string): Promise<boolean> {
  try {
    await Deno.stat(path);
    return true;
  } catch {
    return false;
  }
}

Deno.test("init agents is idempotent for an existing non-minimal AGENTS.md", async () => {
  const testRepo = await createTestRepo({
    initialFiles: {
      "AGENTS.md": EXISTING_AGENTS_MD,
    },
  });

  try {
    const firstRun = await runDnCommand(["init", "agents"], {
      cwd: testRepo.path,
    });
    const firstContent = await Deno.readTextFile(`${testRepo.path}/AGENTS.md`);

    const secondRun = await runDnCommand(["init", "agents"], {
      cwd: testRepo.path,
    });
    const secondContent = await Deno.readTextFile(`${testRepo.path}/AGENTS.md`);

    assert(firstRun.stdout.includes("Updated"));
    assert(secondRun.stdout.includes("Updated"));
    assertEquals(secondContent, firstContent);
    assertEquals(secondContent.match(/^## Using dn$/gm)?.length ?? 0, 1);
  } finally {
    await cleanupTestRepo(testRepo);
  }
});

Deno.test("--skill without --agent fails and writes nothing", async () => {
  const testRepo = await createTestRepo();

  try {
    const result = await runDnCommand(["init", "agents", "--skill"], {
      cwd: testRepo.path,
      expectFailure: true,
    });

    assert(result.stderr.includes("requires --agent"));
    assert(!await pathExists(`${testRepo.path}/AGENTS.md`));
    assert(!await pathExists(`${testRepo.path}/.agents`));
    assert(!await pathExists(`${testRepo.path}/.claude`));
    assert(!await pathExists(`${testRepo.path}/.cursor`));
  } finally {
    await cleanupTestRepo(testRepo);
  }
});

Deno.test("repo skill install writes only the selected codex files", async () => {
  const testRepo = await createTestRepo();

  try {
    await runDnCommand(["init", "agents", "--skill", "--agent", "codex"], {
      cwd: testRepo.path,
    });

    const skillPath = `${testRepo.path}/.agents/skills/dn/SKILL.md`;
    const openAiMetadataPath =
      `${testRepo.path}/.agents/skills/dn/agents/openai.yaml`;
    const skillContent = await Deno.readTextFile(skillPath);

    assert(skillContent.includes("name: dn"));
    assert(skillContent.includes("Generated by dn init agents --skill"));
    assert(await pathExists(openAiMetadataPath));
    assert(!await pathExists(`${testRepo.path}/AGENTS.md`));
    assert(!await pathExists(`${testRepo.path}/.claude`));
    assert(!await pathExists(`${testRepo.path}/.cursor`));
  } finally {
    await cleanupTestRepo(testRepo);
  }
});

Deno.test("repo cursor skill install writes cursor rule only", async () => {
  const testRepo = await createTestRepo();

  try {
    await runDnCommand(["init", "agents", "--skill", "--agent", "cursor"], {
      cwd: testRepo.path,
    });

    const cursorRulePath = `${testRepo.path}/.cursor/rules/dn.mdc`;
    const cursorRule = await Deno.readTextFile(cursorRulePath);

    assert(cursorRule.includes(".agents/skills/dn/SKILL.md"));
    assert(!await pathExists(`${testRepo.path}/AGENTS.md`));
    assert(!await pathExists(`${testRepo.path}/.agents`));
    assert(!await pathExists(`${testRepo.path}/.claude`));
  } finally {
    await cleanupTestRepo(testRepo);
  }
});

Deno.test("user skill install writes to mocked home for supported agents", async () => {
  const home = await Deno.makeTempDir({ prefix: "dn-test-home-" });
  const agents = ["codex", "opencode", "claude"] as const;

  try {
    for (const agent of agents) {
      const testRepo = await createTestRepo();
      try {
        await runDnCommand([
          "init",
          "agents",
          "--skill",
          "--agent",
          agent,
          "--scope",
          "user",
        ], {
          cwd: testRepo.path,
          env: { DN_INIT_AGENTS_HOME: home },
        });
      } finally {
        await cleanupTestRepo(testRepo);
      }
    }

    assert(await pathExists(`${home}/.agents/skills/dn/SKILL.md`));
    assert(await pathExists(`${home}/.agents/skills/dn/agents/openai.yaml`));
    assert(await pathExists(`${home}/.claude/skills/dn/SKILL.md`));
  } finally {
    await Deno.remove(home, { recursive: true }).catch(() => {});
  }
});

Deno.test("user cursor skill install fails clearly", async () => {
  const testRepo = await createTestRepo();
  const home = await Deno.makeTempDir({ prefix: "dn-test-home-" });

  try {
    const result = await runDnCommand([
      "init",
      "agents",
      "--skill",
      "--agent",
      "cursor",
      "--scope",
      "user",
    ], {
      cwd: testRepo.path,
      env: { DN_INIT_AGENTS_HOME: home },
      expectFailure: true,
    });

    assert(result.stderr.includes("Cursor skill installation is repo-scoped"));
    assert(!await pathExists(`${home}/.cursor`));
  } finally {
    await cleanupTestRepo(testRepo);
    await Deno.remove(home, { recursive: true }).catch(() => {});
  }
});

Deno.test("existing unmarked skill conflicts without force", async () => {
  const testRepo = await createTestRepo({
    initialFiles: {
      ".agents/skills/dn/SKILL.md": "custom local skill\n",
    },
  });

  try {
    const result = await runDnCommand([
      "init",
      "agents",
      "--skill",
      "--agent",
      "codex",
    ], {
      cwd: testRepo.path,
      expectFailure: true,
    });
    const skillContent = await Deno.readTextFile(
      `${testRepo.path}/.agents/skills/dn/SKILL.md`,
    );

    assert(result.stderr.includes("Refusing to overwrite unmanaged"));
    assertEquals(skillContent, "custom local skill\n");
    assert(
      !await pathExists(
        `${testRepo.path}/.agents/skills/dn/agents/openai.yaml`,
      ),
    );
  } finally {
    await cleanupTestRepo(testRepo);
  }
});

Deno.test("--dry-run --json reports planned writes without changing files", async () => {
  const testRepo = await createTestRepo();

  try {
    const result = await runDnCommand([
      "init",
      "agents",
      "--skill",
      "--agent",
      "claude",
      "--dry-run",
      "--json",
    ], {
      cwd: testRepo.path,
    });

    const report = JSON.parse(result.stdout) as {
      results: Array<{ path: string; status: string; reason: string }>;
    };

    assertEquals(report.results.length, 1);
    assert(report.results[0].path.endsWith("/.claude/skills/dn/SKILL.md"));
    assertEquals(report.results[0].status, "write");
    assertEquals(report.results[0].reason, "missing");
    assert(!await pathExists(`${testRepo.path}/.claude`));
    assert(!await pathExists(`${testRepo.path}/AGENTS.md`));
  } finally {
    await cleanupTestRepo(testRepo);
  }
});

Deno.test("repo base-image skill install writes named skill files", async () => {
  const testRepo = await createTestRepo();

  try {
    await runDnCommand([
      "init",
      "agents",
      "--skill",
      "base-image",
      "--agent",
      "opencode",
    ], {
      cwd: testRepo.path,
    });

    const skillPath = `${testRepo.path}/.agents/skills/base-image/SKILL.md`;
    const openAiMetadataPath =
      `${testRepo.path}/.agents/skills/base-image/agents/openai.yaml`;
    const skillContent = await Deno.readTextFile(skillPath);

    assert(skillContent.includes("name: base-image"));
    assert(skillContent.includes("sandbox.docker.dockerfile"));
    assert(skillContent.includes("Generated by dn init agents --skill"));
    assert(await pathExists(openAiMetadataPath));
    assert(!await pathExists(`${testRepo.path}/.agents/skills/dn`));
    assert(!await pathExists(`${testRepo.path}/AGENTS.md`));
  } finally {
    await cleanupTestRepo(testRepo);
  }
});

Deno.test("unsupported skill name fails clearly", async () => {
  const testRepo = await createTestRepo();

  try {
    const result = await runDnCommand([
      "init",
      "agents",
      "--skill",
      "not-a-skill",
      "--agent",
      "opencode",
    ], {
      cwd: testRepo.path,
      expectFailure: true,
    });

    assert(result.stderr.includes('Unsupported skill name "not-a-skill"'));
    assert(!await pathExists(`${testRepo.path}/.agents`));
  } finally {
    await cleanupTestRepo(testRepo);
  }
});
